name: chunked-decomp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - pip
  - pip:
    - transformers>=4.30.0
    - datasets>=2.10.0
    - accelerate>=0.20.0
    - wandb>=0.15.0
    - tqdm>=4.65.0
