# HPC Cluster Configuration

# SLURM job settings
slurm:
  default_job:
    partition: "gpu"
    nodes: 1
    ntasks_per_node: 1
    cpus_per_task: 8
    gres: "gpu:1"
    mem: "32G"
    time: "24:00:00"
  
  memory_benchmark:
    partition: "gpu"
    nodes: 1
    ntasks_per_node: 1
    cpus_per_task: 4
    gres: "gpu:1"
    mem: "64G"
    time: "12:00:00"
  
  large_experiment:
    partition: "gpu"
    nodes: 1
    ntasks_per_node: 1
    cpus_per_task: 16
    gres: "gpu:2"
    mem: "128G"
    time: "48:00:00"

# Environment modules (adjust for your cluster)
modules:
  - "python/3.9"
  - "cuda/11.8"
  - "gcc/9.3.0"

# Paths
paths:
  home: "/home/username"
  scratch: "/scratch/username"
  data_dir: "/scratch/username/chunked-decomp/data"
  results_dir: "/scratch/username/chunked-decomp/results"

# Resource limits
resources:
  max_memory_gb: 64
  max_gpu_count: 2
  max_cpu_count: 32
  max_time_hours: 72
