# Compression Configuration for ChunkedDecomp

# Default compression settings
default_compression:
  chunk_size: 16
  block_size: 64
  compression_ratios: [0.25, 0.5, 0.75]
  adaptive_rank: true

# Chunking configurations
chunking:
  small_chunks:
    chunk_size: 8
    description: "Small chunks for fine-grained compression"
  
  medium_chunks:
    chunk_size: 16
    description: "Medium chunks (default)"
  
  large_chunks:
    chunk_size: 32
    description: "Large chunks for coarse compression"

# Block size configurations
block_sizes:
  small: 32
  medium: 64
  large: 128
  xlarge: 256

# Compression strategies
compression_strategies:
  uniform:
    description: "Uniform compression across all chunks"
    rank_strategy: "uniform"
    base_compression_ratio: 0.5
  
  adaptive:
    description: "Adaptive compression based on chunk importance"
    rank_strategy: "adaptive"
    importance_threshold: 0.1
    min_compression_ratio: 0.25
    max_compression_ratio: 0.75
  
  progressive:
    description: "Progressive compression (early chunks less compressed)"
    rank_strategy: "progressive"
    start_ratio: 0.75
    end_ratio: 0.25

# Quality control
quality_control:
  max_reconstruction_error: 0.1
  error_monitoring: true
  adaptive_rank_adjustment: true
  rank_adjustment_threshold: 0.05
